version: '3'

services:
  postgres:
    # renovate datasource=custom.scalingo-postgres depName=postgres
    image: postgres:14.8-alpine
    container_name: pix-api-postgres
    ports:
      - '${PIX_DATABASE_PORT:-5432}:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  redis:
    # renovate datasource=custom.scalingo-redis depName=redis
    image: redis:7.2.3-alpine
    container_name: pix-api-redis
    ports:
      - '${PIX_CACHE_PORT:-6379}:6379'
