name: Auto Rebase PRs with Auto-Merge Enabled

on:
  push:
    branches:
      - dev

jobs:
  auto-rebase:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Auto Rebase PRs with Auto-Merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e

          LATEST_COMMIT_REF=$(git rev-parse HEAD)
          PRS=$(gh pr list --state open --json number,autoMergeRequest,headRefName,baseRefName,baseRefOid)

          echo "$PRS" | jq -c '.[]' | while read pr; do
              NUMBER=$(echo "$pr" | jq -r '.number')
              AUTO_MERGE=$(echo "$pr" | jq '.autoMergeRequest')
              HEAD_REF=$(echo "$pr" | jq -r '.headRefName')
              BASE_REF=$(echo "$pr" | jq -r '.baseRefName')
              BASE_REF_OID=$(echo "$pr" | jq -r '.baseRefOid')

              if [[ "$AUTO_MERGE" != "null" && "$BASE_REF" == "dev" ]]; then
                  echo "🔍 PR #$NUMBER : Auto-merge activé"
                  echo "BASE_REF $BASE_REF_OID"
                  echo "LATEST_COMMIT_REF $LATEST_COMMIT_REF"
                  if [[ "$BASE_REF_OID" != "$LATEST_COMMIT_REF" ]]; then
                      echo "🔄 PR #$NUMBER est en retard sur dev → Rebase en cours"
                      git fetch origin $HEAD_REF
                      echo "Checkout $HEAD_REF"
                      git checkout $HEAD_REF
                      git rebase origin/dev || (echo "Conflit détecté : abandon du rebase." && git rebase --abort)

                      git push origin --force-with-lease
                      echo "✅ PR #$NUMBER rebasée avec succès"
                  else
                      echo "✅ PR #$NUMBER est déjà à jour"
                  fi
              fi
          done
